project_id = "uokiiigxdblvmhmxsdvw"

[functions.read-jira-story]
verify_jwt = false

[functions.generate-testplan]
verify_jwt = false

[functions.approve-testplan]
verify_jwt = false

[functions.parse-test-cases]
verify_jwt = false

[functions.generate-details]
verify_jwt = false

[functions.get-qmetry-folders]
verify_jwt = false

[functions.export-to-qmetry]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.manage-api-keys]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
